### ISSUE TITLE
fix: Make the app build on iOS properly

### ISSUE THREAD

**Issue by roshangm1** [tony-xlh/vision-camera-cropper#1]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I wasn't able to build the app with these changes. Looks like, `VisionCameraCropper-Swift.h` does not exist in the project. I have removed it and changed few other things that fixed the issue for me.

Here is the change #2

**Comment by xulihang** [comment]
I follow this project: https://github.com/ismaelsousa/vision-camera-ocr/tree/v2/ios and `VisionCameraCropper-Swift.h` will be generated automatically in my case.

I am not sure whether we need to make the changes.

**Comment by roshangm1** [comment]
> I follow this project: https://github.com/ismaelsousa/vision-camera-ocr/tree/v2/ios and `VisionCameraCropper-Swift.h` will be generated automatically in my case.
> 
> I am not sure whether we need to make the changes.

hmm well. for some reason, that file didn't show up for me. weird.

**Comment by Anj-interactivated** [comment]
getting the same error as @roshangm1 . @xulihang can you merge the fix, please ?
