### ISSUE TITLE
passing non integer values to cropRegion ignores the crop setting (ios, maybe android as well)

### ISSUE THREAD

**Issue by Anj-interactivated** [tony-xlh/vision-camera-cropper#4]
Was passing cropRegion.left = 14.5 (non integer) then value was ignored when cropping . Full width of image was taken
I think this can be easly solved by adding Math.round inlines below. Do not think adding it there will impact performance but it can cause unexpected rounding ...  
vision-camera-cropper/src/index.tsx
 
```
      cropRegionRecord["left"] = config.cropRegion.left;
      cropRegionRecord["top"] = config.cropRegion.top;
      cropRegionRecord["width"] = config.cropRegion.width;
      cropRegionRecord["height"] = config.cropRegion.height;
```

**Comment by xulihang** [comment]
I am not sure why float values are not supported. Based on the code, it should be supported.
