### ISSUE TITLE
Not building in react-native-vision-camera 4.5.0

### ISSUE THREAD

**Issue by johnernest02-automanager** [tony-xlh/vision-camera-cropper#6]
> Task :vision-camera-cropper:compileDebugJavaWithJavac FAILED
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/BitmapUtils.java:36: error: package com.mrousavy.camera.frameprocessor does not exist
import com.mrousavy.camera.frameprocessor.Frame;
                                         ^
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/BitmapUtils.java:37: error: package com.mrousavy.camera.types does not exist
import com.mrousavy.camera.types.Orientation;
                                ^
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/BitmapUtils.java:74: error: cannot find symbol
    public static Bitmap getBitmap(Frame image) throws FrameInvalidError {
                                   ^
  symbol:   class Frame
  location: class BitmapUtils
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/BitmapUtils.java:87: error: cannot find symbol
    public static int getRotationDegreeFromOrientation(Orientation orientation) {
                                                       ^
  symbol:   class Orientation
  location: class BitmapUtils
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/VisionCameraCropperPackage.java:9: error: package com.mrousavy.camera.frameprocessor does not exist
import com.mrousavy.camera.frameprocessor.FrameProcessorPluginRegistry;
                                         ^
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/CropperFrameProcessorPlugin.java:9: error: package com.mrousavy.camera.frameprocessor does not exist
import com.mrousavy.camera.frameprocessor.Frame;
                                         ^
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/CropperFrameProcessorPlugin.java:10: error: package com.mrousavy.camera.frameprocessor does not exist
import com.mrousavy.camera.frameprocessor.FrameProcessorPlugin;
                                         ^
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/CropperFrameProcessorPlugin.java:11: error: package com.mrousavy.camera.frameprocessor does not exist
import com.mrousavy.camera.frameprocessor.VisionCameraProxy;
                                         ^
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/CropperFrameProcessorPlugin.java:19: error: cannot find symbol
public class CropperFrameProcessorPlugin extends FrameProcessorPlugin {
                                                 ^
  symbol: class FrameProcessorPlugin
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/CropperFrameProcessorPlugin.java:20: error: cannot find symbol
  CropperFrameProcessorPlugin(@NonNull VisionCameraProxy proxy, @Nullable Map<String, Object> options) {super();}
                                       ^
  symbol:   class VisionCameraProxy
  location: class CropperFrameProcessorPlugin
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/CropperFrameProcessorPlugin.java:24: error: cannot find symbol
  public Object callback(@NonNull Frame frame, @Nullable Map<String, Object> arguments) {
                                  ^
  symbol:   class Frame
  location: class CropperFrameProcessorPlugin
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/BitmapUtils.java:88: error: package Orientation does not exist
        if (orientation.getUnionValue().equals(Orientation.PORTRAIT.getUnionValue())) {
                                                          ^
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/BitmapUtils.java:90: error: package Orientation does not exist
        }else if (orientation.getUnionValue().equals(Orientation.LANDSCAPE_LEFT.getUnionValue())) {
                                                                ^
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/BitmapUtils.java:92: error: package Orientation does not exist
        } else if (orientation.getUnionValue().equals(Orientation.LANDSCAPE_RIGHT.getUnionValue())) {
                                                                 ^
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/BitmapUtils.java:94: error: package Orientation does not exist
        }else if (orientation.getUnionValue().equals(Orientation.PORTRAIT_UPSIDE_DOWN.getUnionValue())) {
                                                                ^
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/VisionCameraCropperPackage.java:17: error: cannot find symbol
    FrameProcessorPluginRegistry.addFrameProcessorPlugin("crop", CropperFrameProcessorPlugin::new);
    ^
  symbol:   variable FrameProcessorPluginRegistry
  location: class VisionCameraCropperPackage
/Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/CropperFrameProcessorPlugin.java:23: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: /Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/VisionCameraCropperModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/admin/Documents/Projects/Project/Project-mobile/node_modules/vision-camera-cropper/android/src/main/java/com/visioncameracropper/CropperFrameProcessorPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by xulihang** [comment]
Vision camera keeps bringing breaking changes. I just grow tired of keeping up with it. PRs are welcome.

**Comment by PrinceUBS** [comment]
I have same issue.
<img width="485" alt="Screenshot 2024-07-26 at 10 09 17 AM" src="https://github.com/user-attachments/assets/bb3b1285-cfdd-4302-a4f9-3ebfb70f6131">
`"react-native-vision-camera": "^4.5.0"`
`"vision-camera-cropper": "^1.1.1"`

**Comment by johnernest02-automanager** [comment]
Anybody know a hint how to fix this? I am successfully building on iOS though

**Comment by PrinceUBS** [comment]
> Anybody know a hint how to fix this? I am successfully building on iOS though

How?

**Comment by johnernest02-automanager** [comment]
Just the usual `npm run ios`. I got no problems on iOS at all

**Comment by PrinceUBS** [comment]
```
 use_frameworks! :linkage => :static
 $RNFirebaseAsStaticFramework = true
```
I'm using firebase, so due to above configuration am i facing the issue? @tony-xlh !

**Comment by xulihang** [comment]
I've updated the plugin to fix this. I think it is related to this line: https://github.com/tony-xlh/vision-camera-cropper/blob/f0fd2571a6c5eca89b7a8c56a2da6fafabd0a070/src/index.tsx#L21
